version: 0.2

phases:
  install:
    commands:
      - pwd
      - ls
  pre_build:
    commands:
      - echo prebuild phase
  build:
    commands:
      - echo  build phase 
  post_build:
    commands:
      - echo post build phase 
